---
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: "wabenet/wabe-project-build:v0.3.11"
      options: --user runner
    steps:
      - uses: wabenet/project-template/actions/build@v0.3.11
        with:
          release: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
